apiVersion: v1
kind: Pod
metadata:
  name: hellodhondhu
  labels:
    app.kubernetes.io/name: hellodhondhu
    app: myapp
spec:
  containers:
  - name: firefox
    image: linuxserver/firefox
    ports:
      - containerPort: 80

--- 

apiVersion: v1
kind: Pod
metadata:
  name: hellotondu
  labels:
    app.kubernetes.io/name: hellotondu
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: hellorondu
  labels:
    app.kubernetes.io/name: hellorondu
    app: myapp
spec:
  containers:
  - name: insta
    image: siddharthdoccker/insta-img:v1
    ports:
      - containerPort: 80